server:
  port: 9001

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# 提供者服务名
service-url:
  nacos-provider-service: http://nacos-payment-provider
