server:
  port: 9193

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      kafka:
        binder:
          brokers: k8s-master:9092
          auto-create-topics: true
      bindings: 
        input:
          destination: stream-kafka
          content-type: application/json
          group: consumer-group-1 # 自定义组名

eureka:
  client:
    service-url: 
      defaultZone: http://eureka7003:7003/eureka
  instance:
    hostname: stream-consumer-9193
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
