server:
  port: 9001

spring:
  application:
    name: cloud-order-service
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka

ribbon:
  ReadTimeout: 5000 #建立连接所用时间
  ConnectTimeout: 5000 # 建立连接后读取服务端资源所用时间

logging:
  level: 
    com.example.cloud.service.PaymentFeignService: debug