server:
  port: 12345

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&useSSL=false&characterEnacoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 97714

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.demo.bean