server:
  port: 12345
#  servlet:
#    context-path: /mvc

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#      static-path-pattern: /res/**

  resources:
#    static-locations: classpath:static
    add-mappings: true


