server:
  port: 9102

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848
        server-addr: k8s131-master:12345 # nginx地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
